trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npx playwright install
    displayName: "Install Dependencies"

  - script: |
      npm test
    continueOnError: true
    displayName: "Test with Playwright"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/junit.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)"
      mergeTestResults: true
      failTaskOnFailedTests: false
    displayName: Publish Test Results

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: test-results
      artifact: junit-xml
    displayName: Publish Downloadable JUnit XML

  - task: PublishPipelineArtifact@1
    inputs:
      path: "$(System.DefaultWorkingDirectory)/playwright-report"
      artifact: html-report
    displayName: Publish Downloadable HTML report
