trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npx playwright install
    displayName: "Install Dependencies"

  - script: |
      npm test
    displayName: "Test with Playwright"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/junit-results.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)"
      mergeTestResults: true
      failTaskOnFailedTests: false
    displayName: Publish Test Results

  - script: |
      if [ "$(TestResultFailures)" != "0" ]; then
        echo "##vso[task.complete result=SucceededWithIssues;]"
      fi
    displayName: Set Job Status to Amber on Failures

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: test-results
      artifact: junit-xml
    displayName: Publish JUnit XML
