trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npx playwright install
    displayName: "Install Dependencies"

  - script: |
      npm test
    continueOnError: true
    displayName: "Test with Playwright"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(System.DefaultWorkingDirectory)/junit.xml"
      artifact: junit-report
    condition: always()
    displayName: "Publish JUnit Report"

  - task: PublishPipelineArtifact@1
    inputs:
      path: "$(System.DefaultWorkingDirectory)/playwright-report"
      artifact: html-report
    displayName: Publish HTML Report
